export const products = [
  { id: 1, name: 'Men hoodie', price: 540, size: 'S M L XL', color: 'grey', image: `${process.env.PUBLIC_URL}/images/textile1.jpg` },
  { id: 2, name: 'Typographic print Crew-Neck T-shirt', price: 850, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile2.jpg` },
  { id: 3, name: 'Women Basic Daisy Regular Fit T-shirt', price: 300, size: 'S M L XL', color: 'yellow', image: `${process.env.PUBLIC_URL}/images/textile3.jpg` },
  { id: 4, name: 'Loose Fit Crew-Neck T-Shirt', price: 430, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile4.jpg` },
  { id: 5, name: 'Oversized Fit T-Shirt', price: 300, size: 'S M L XL', color: 'white', image: `${process.env.PUBLIC_URL}/images/textile5.jpg` },
  { id: 6, name: 'Graphic Regular Fit T-Shirt', price: 290, size: 'S M L XL', color: 'Brown', image: `${process.env.PUBLIC_URL}/images/textile6.jpg` },
  { id: 7, name: 'Oversized Fit Crew-Neck T-Shirt', price: 400, size: 'S M L XL', color: 'white', image: `${process.env.PUBLIC_URL}/images/textile7.jpg` },
  { id: 8, name: 'Women Loosie Fit V-Neck T-Shirt', price: 320, size: 'S M L XL', color: 'green', image: `${process.env.PUBLIC_URL}/images/textile8.jpg` },
  { id: 9, name: 'Regular Fit T-Shirt with placement Logo', price: 700, size: 'S M L XL', color: 'yellow', image: `${process.env.PUBLIC_URL}/images/textile9.jpg` },
  { id: 10, name: 'Typographic print Crew-Neck T-shirt', price: 300, size: 'S M L XL', color: 'blue', image: `${process.env.PUBLIC_URL}/images/textile10.jpg` },
  { id: 11, name: 'Regular Fit T-Shirt with placement Logo', price: 900, size: 'S M L XL', color: 'blue', image: `${process.env.PUBLIC_URL}/images/textile11.jpg` },
  { id: 12, name: 'Brand Icon Print Crew-Neck T-shirt', price: 850, size: 'S M L XL', color: 'white', image: `${process.env.PUBLIC_URL}/images/textile12.jpg` },
  { id: 13, name: 'Relaxed Fit T-SHIRT', price: 600, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile13.jpg` },
  { id: 14, name: 'Regular Fit T-Shirt with placement Logo', price: 350, size: 'S M L XL', color: 'green', image: `${process.env.PUBLIC_URL}/images/textile14.jpg` },
  { id: 15, name: 'Twist-Knot Relaxed Fit T-Shirt', price: 410, size: 'S M L XL', color: 'blue', image: `${process.env.PUBLIC_URL}/images/textile15.jpg` },
  { id: 16, name: 'Classics Oversized T-shirt', price: 650, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile16.jpg` },
  { id: 17, name: 'Oversized Fit T-Shirt', price: 390, size: 'S M L XL', color: 'blue', image: `${process.env.PUBLIC_URL}/images/textile17.jpg` },
  { id: 18, name: 'Mickey Sketch Crew-Neck T-Shirt', price: 450, size: 'S M L XL', color: 'yellow', image: `${process.env.PUBLIC_URL}/images/textile18.jpg` },
  { id: 19, name: 'Printed Crew-Neck T-Shirt', price: 600, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile19.jpg` },
  { id: 20, name: 'Oversized Fit polo T-Shirt', price: 480, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile20.jpg` },
  { id: 21, name: 'Printed Slim Fit Crew-Neck T-Shirt', price: 500, size: 'S M L XL', color: 'black', image: `${process.env.PUBLIC_URL}/images/textile21.jpg` },
  { id: 22, name: 'Graphic Regular Fit T-Shirt', price: 480, size: 'S M L XL', color: 'white', image: `${process.env.PUBLIC_URL}/images/textile22.jpg` },
  { id: 23, name: 'LooseFit Crew-Neck T-Shirt', price: 800, size: 'S M L XL', color: 'white', image: `${process.env.PUBLIC_URL}/images/textile23.jpg` },
  { id: 24, name: 'Regular Fit T-Shirt', price: 550, size: 'S M L XL', color: 'blue', image: `${process.env.PUBLIC_URL}/images/textile24.jpg` },
];